### ISSUE TITLE
[bug?] Failed to load cursor theme

### ISSUE THREAD

**Issue by revuwa** [vars1ty/HybridBar#18]
It's not a big deal, but I thought I tell, that I get the following warning at bar startup:
`(hybrid-bar:969272): Gdk-WARNING **: 17:27:33.684: Failed to load cursor theme Dracula-cursors`
[Dracula](https://draculatheme.com/)-cursors is the cursor theme I use, which is respected from any other GTK app, (incl. waybar) on my system (NixOS). Debug output doesn't say any more on that.

This ends up that I have my cursor theme anywhere, but on hovering over HybridBar.
I found an issue of an other app with a clip (.mp4 in the first post), which shows how you could imaging that:
https://github.com/alacritty/alacritty/issues/5990

It would be really cool, if this could be fixed sometime in the future.
If i can serve with further information, please just let me know.

**Comment by vars1ty** [comment]
Hm, weird since I don't have this issue. I could look into it in the coming days though

**Comment by vars1ty** [comment]
Seems to be an issue with GTK3, downgrade to `3.24.34` and check, since I remember seeing people mention cursor theme issues in Hyprland's Discord related to other applications too.
