### ISSUE TITLE
[feature-request] Idle-Inhibitor

### ISSUE THREAD

**Issue by revuwa** [vars1ty/HybridBar#20]
> feel free to suggest widgets

So I do, because I'm missing one little thingy, (next to a system tray; I know you considering, and I very appreciate that), after switching over (from waybar) -> [Idle-Inhibitor](https://wayland.app/protocols/idle-inhibit-unstable-v1) (which is a [waybar module](https://github.com/Alexays/Waybar/blob/4e256cf3f0df8a404b4f40724a41dca1ad1c5cea/src/modules/idle_inhibitor.cpp#L49) who ["can inhibit idle behavior such as screen blanking, locking, and screensaving, also known as presentation mode."](https://github.com/Alexays/Waybar/wiki/Module:-Idle-Inhibitor)).

It would be great, if there could be such a functionality, e. g. as a toggle button, or whatever to inhibit idle with HybridBar as well. Something, which could set one of the following status manually:
```
"activated": "▶"
"deactivated": "▷"
```
If you like the idea, I don't know if the following references could help in any way 🤷

- [Hyprland "added support for wlr_idle_inhibitor_v1"](https://github.com/hyprwm/Hyprland/commit/9655d0c13822bdaa5d86fd1153c27c184fd55253) (of course it's a [Wayland protocol](https://wayland.app/protocols/idle-inhibit-unstable-v1), not Hyprland specific)
- [Rust project which "Inhibits idle on Wayland during media playback by an MPRIS2 player"](https://github.com/sameer/wl-mpris-idle-inhibit)
- [Rust project which "Inhibits idle on Wayland when a video device is open"](https://github.com/sameer/wl-video-idle-inhibit)

If not, never mind - it was worth a shot ✌️

**Comment by vars1ty** [comment]
If I decide to try and mess with Wayland Protocols in Hybrid (which would at first be for workspaces), then I could look into this 😄

**Comment by revuwa** [comment]
Sounds fair enough 🙃

[off-topic on]
For (Hyprland) workspaces I made an ugly workaround (@`.config/HybridBar/config.json`) in the meanwhile:
```
    "left-label_workspaces": {
        "command": "for i in $(hyprctl workspaces -j | jq -r 'sort_by(.id) | .[].id'); do if [[ $i == $(hyprctl monitors -j | jq -r '.[].activeWorkspace.id') ]]; then echo [$i] | tr '\n' ' '; else echo $i | tr '\n' ' '; fi; done"
    },
```
which results in a dynamic workspace number list, with active workspace in square brackets:
![Workspaces](https://user-images.githubusercontent.com/7300276/201526456-5f2873c5-533a-45bb-bd9a-fcb101440a29.png)
[off-topic off]

**Comment by revuwa** [comment]
Alternatively there seems to be a possibility (to [un|inhibit]) via GTK, too:
https://arnaudr.io/2020/09/25/inhibit-suspending-the-computer-with-gtkapplication/

**Comment by vars1ty** [comment]
> For (Hyprland) workspaces I made an ugly workaround (@.config/HybridBar/config.json) in the meanwhile

Looks cool, nice job!

> Alternatively there seems to be a possibility (to [un|inhibit]) via GTK, too

Assuming it doesn't require some weird hacky workarounds (haven't looked into it fully, yet), then I may be able to get it working for the next version.
Although since I don't let my PC go into sleep mode, it would be released then be released without tests on my part. If it doesn't end up working, then feel free to post about it here 👍🏽

**Comment by vars1ty** [comment]
Commit e0f38f938544c5d69b6eb0a53cb46b35c031b558 adds experimental support for it, preventing your pc from entering the `IDLE` state. Please check if it works and if it does, then I'll mark it as functional

**Comment by revuwa** [comment]
WOW, thanks for giving this a try.

I tried this with `"inhibit": true` in my `config.json`, which results in a message at bar's startup:
`(hybrid-bar:1158194): Gtk-WARNING **: 19:31:56.973: Calling org.freedesktop.portal.Inhibit.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Inhibit” on object at path /org/freedesktop/portal/desktop`

This could have something to do with my - let's say - "atypical" Linux distri (NixOS), and/or missing features 🤷
So I tested anyway, if my monitor goes to sleep, and it does. With other words, sadly this doesn't work for me.

If you - or other people - want to test this, too, you could use [swayidle](https://github.com/swaywm/swayidle) + [swaylock](https://github.com/swaywm/swaylock), e. g. with the following parameters:

- Hyprland related:
`swayidle -w timeout 30 'swaylock' timeout 35 'hyprctl dispatch dpms off' resume 'hyprctl dispatch dpms on' before-sleep 'swaylock'`
- Sway related:
`swayidle -w timeout 30 swaylock timeout 35 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' before-sleep swaylock`

With this running, your system should (graphically) get locked after 30 seconds and your monitor should turn off 5 seconds after locking (35 sec in total). Of course this low values are for testing reasons only.

**Comment by vars1ty** [comment]
The missing portal is indeed an issue on your end, perhaps you are missing the GTK portal?

**Comment by vars1ty** [comment]
Alright an update: I tried inhibit myself, even with **all** of the inhibit flags; it doesn't work. So I'll look into some of the Wayland protocols and unless my brain takes a 360' into a concrete wall, it should be ready for the next release.

**Comment by vars1ty** [comment]
Upon further inspection into crates that implement Wayland protocols, it gave me more aids than anything, therefore I won't be working on this *yet* as I'm working on other projects as well.

So if anyone else with more experience than me wants to in the meantime, they are free to implement Inhibit / Workspaces **in a clean way** if they want to. Otherwise I'll *probably* do it in the future when I got more time.

**Comment by revuwa** [comment]
> The org.freedesktop.portal.Inhibit is indeed an issue on your end, perhaps you are missing the GTK portal?

I tried (several times) to get portals to work, and they "seems" to work, but don't really does, if I want to use them, e. g. for screen recording, which doesn't work on my sidem, too 🤷 Because I don't rely on it, I not invested too much time, for now.

And thanks again for looking into this, sometime. Even if not, big thanks for your efforts up to here 💖

**Comment by revuwa** [comment]
I'm sorry that I missed that Hyprland implemented [inhibit_idle windowrule](https://github.com/hyprwm/Hyprland/commit/a69fd21a1ac90c24cee659595d62329f8638d632) in the meanwhile.
With this I can exactly adjust, when idle inhibition should be triggered, and when not. [Sway](https://github.com/swaywm/sway/blob/master/sway/commands/inhibit_idle.c) does have such a functionality, too.

If it's up to me, no more effort needs to be put in here, and the issue could be closed, unless other people or yourself like to pursue the idea further.
