### ISSUE TITLE
[bug?] HybridBar disappear if fullscreen window opens on other workspace

### ISSUE THREAD

**Issue by revuwa** [vars1ty/HybridBar#23]
You could try to reproduce that behavior with something like this:
```
windowrule = workspace 10 silent,foot-test
bind = $mainMod SHIFT, I, exec, foot -F -a 'foot-test'
```
in your `~/.config/hypr/hyprland.conf`, which opens a [foot](https://codeberg.org/dnkl/foot) terminal (in fullscreen mode) on workspace 10.
If you're not currently at workspace 10, then HybridBar becomes invisible, until you change your workspace to any other workspace, e. g. to 5, or whatever.

I think it's intentional that HybridBar disappears if a fullscreen apps comes up, but it would be cool, if the bar could check, if the fullscreen app is opened at current workspace, to avoid disappearing otherwise.

If you (understandably) ask what usecase could need to open a fullscreen app silently (on other workspace), then mine would be playing around with idle inhibition, (related to: https://github.com/vars1ty/HybridBar/issues/20), for example by adding the following:
`windowrulev2 = idleinhibit fullscreen,class:^(foot-test)$`
in your `~/.config/hypr/hyprland.conf` to inhibit idle only, if the specified window/app is in fullscreen, and in this case it would be great, if this window comes up silently, so you could toggle fullscreen mode of the window to activate/disable inhibition as you like.

Sure, this usecase is a first class edge case, but I thought I report this behavior, anyway 🙃

**Comment by vars1ty** [comment]
If it disappears on a different workspace when going fullscreen, then that's something the compositor is responsible for since Hybrid doesn't deal with any of that logic on its own

**Comment by revuwa** [comment]
> If it disappears when a window on a different workspace goes fullscreen, then that's something the compositor is responsible for since Hybrid doesn't deal with any of that logic on its own

Thanks for the response. Just wanted to let you know, then 😅
