### ISSUE TITLE
[feature-request] option to execute background command/s

### ISSUE THREAD

**Issue by revuwa** [vars1ty/HybridBar#24]
Related to https://github.com/vars1ty/HybridBar/issues/20 I tried to rebuild such [waybar's](https://github.com/Alexays/Waybar) idle_inhibitor like functionality. So I made a little menue with [bemenu](https://github.com/Cloudef/bemenu):

```
    "right-button_idleinhibition": {
        "update_rate": 0,
        "text": "☯",
        "command": "slc=$(echo -e \"10 minutes\n1 hour\n1 day\" | bemenu -p 'inhibit idle for:' -i -l 3 -c -W 0.1); if [[ $slc == '10 minutes' ]]; then /var/run/current-system/sw/bin/systemd-inhibit --what=idle --why=HybridBarIdleInhibition sleep 10m & disown; elif [[ $slc == '1 hour' ]]; then /var/run/current-system/sw/bin/systemd-inhibit --what=idle --why=HybridBarIdleInhibition sleep 1h & disown; elif [[ $slc == '1 day' ]]; then /var/run/current-system/sw/bin/systemd-inhibit --what=idle --why=HybridBarIdleInhibition sleep 1d & disown; fi",
        "tooltip": "inhibit idle"
    },
    "right-label_idleinhibition": {
        "update_rate": 1000,
        "command": "if systemd-inhibit --list | grep -q 'HybridBarIdleInhibition'; then echo '⏸ '; else echo '∞ '; fi",
        "tooltip_command": "if systemd-inhibit --list | grep -q 'HybridBarIdleInhibition'; then echo 'idle inhibition active'; else echo 'idle inhibition inactive '; fi"
    },
```
Preview (after clicking the ☯-button):
![image](https://user-images.githubusercontent.com/7300276/203123835-4c06518e-15bb-4918-b7c6-72b5c074a31e.png)
(The theme may vary, I use the following, [inspired by [Dracula theme](https://draculatheme.com/bemenu)] if someone is interested):
`BEMENU_OPTS="--fb '#282A36' --ff '#F1FA8C' --nb '#282A36' --nf '#8BE9FD' --hb '#282A36' --hf '#50FA7B' --ab '#282A36' --af '#BD93F9'"`

Now, the problem is, that if I choose an option, HybridBar freezes for the specified time, even if I try to send the `systemd-inhibit` process to background (with several ways; tried & at the end, too). In other words, HybridBar completely freezes for 10 minutes with the first option. So it seems not to work to send the process to background.

You could reproduze this for example with:
```
    "right-button_idleinhibitionTEST": {
        "update_rate": 0,
        "text": "☯ ",
        "command": "systemd-inhibit --what=idle sleep 5s & disown",
        "tooltip": "inhibit idle TEST"
    },
```
to (hopefully) see HybridBar freezing for 5 seconds, before it comes back to life.
If I execute that same command in a default shell, it'll be but to background as expected:
![image](https://user-images.githubusercontent.com/7300276/203126595-eb753232-2d27-452b-8919-7de99bb01802.png)

For this, and for sure other usecases it would be awesome, if there would be a way to:

- explicit execute/send commands to background, with something like `"command_bg":`, or (possibly better)
- HybridBar respects processes, which will be send to background, like (in this case): `systemd-inhibit --what=idle sleep 5s &`

What do you hink?

**Comment by vars1ty** [comment]
Yeah Hybrid owns all the processes you spawn, you can workaround this issue via `hyprctl dispatch exec [command]` to let the compositor own the process, not Hybrid

**Comment by revuwa** [comment]
Very interesting 💡

So I modified the command above, and it works great:
```
    "right-button_idleinhibition": {
        "update_rate": 0,
        "text": "☯",
        "command": "slc=$(echo -e \"10 minutes\n1 hour\n1 day\" | bemenu -p 'inhibit idle for:' -i -l 3 -c -W 0.1); if [[ $slc == '10 minutes' ]]; then hyprctl dispatch exec \"systemd-inhibit --what=idle --why=HybridBarIdleInhibition sleep 10m\"; elif [[ $slc == '1 hour' ]]; then \"systemd-inhibit --what=idle --why=HybridBarIdleInhibition sleep 1h\"; elif [[ $slc == '1 day' ]]; then \"systemd-inhibit --what=idle --why=HybridBarIdleInhibition sleep 1d\"; fi",
        "tooltip": "inhibit idle"
    },
```
Thank you soooo much!
