### ISSUE TITLE
Unable to run hybrid bar after building it locally

### ISSUE THREAD

**Issue by Srinanda-Yallapragada** [vars1ty/HybridBar#31]
P.S. I am new to building packages so please let me know if I am doing something incorrectly

OS: Nobara Linux 37 
Kernel: 6.1.6-203.fsync.fc37.x86_64 
DE: Hyprland 
GPU: NVIDIA GeForce RTX 3060 Mobile / Max-Q 
AMD Ryzen 9 5900HS with Radeon Graphics

I am hitting this error after I successfully build Hybrid Bar when I try to run it ```./hybrid-bar``` from the command line. 

```'thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/config.rs:11:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)```

 I have copied the example config.json and style.css to ~/.config/HybridBar.
 
 output of  RUST_BACKTRACE=1 ./hybrid-bar 
 
 ```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/config.rs:11:42
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)```
 
Any advice on how to get hybrid-bar working on my fedora-based system?

**Comment by vars1ty** [comment]
Commit 9c59fdde06312c6ea0dfd56efd2451ab86fbead4 should fix it, test and see.

**Comment by Srinanda-Yallapragada** [comment]
Fixed! 

Thanks for the quick response.

**Comment by vars1ty** [comment]
No problems
