### ISSUE TITLE
Doesn't run on OpenSUSE MicroOS after building

### ISSUE THREAD

**Issue by fearlessgeekmedia** [vars1ty/HybridBar#32]
The build seemed to go well. However, when I try to run, I get this error.

thread 'main' panicked at '[ERROR] Failed loading CSS from 'style.css'!', src/main.rs:152:29
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Aborted (core dumped)

That was with RUST_BACKTRACE=1 as it initialy requested I do.

Just ran it with full.

thread 'main' panicked at '[ERROR] Failed loading CSS from 'style.css'!', src/main.rs:152:29
stack backtrace:
   0:     0x555ff1f07f36 - <unknown>
   1:     0x555ff1ea873e - <unknown>
   2:     0x555ff1eeba04 - <unknown>
   3:     0x555ff1f07c0f - <unknown>
   4:     0x555ff1ef77bf - <unknown>
   5:     0x555ff1ef8311 - <unknown>
   6:     0x555ff1f08392 - <unknown>
   7:     0x555ff1f082fc - <unknown>
   8:     0x555ff1ef7bc1 - <unknown>
   9:     0x555ff1e933c2 - <unknown>
  10:     0x555ff1ecc2c6 - <unknown>
  11:     0x7f344c03a570 - g_closure_invoke
  12:     0x7f344c04e416 - <unknown>
  13:     0x7f344c0553b5 - g_signal_emit_valist
  14:     0x7f344c05551f - g_signal_emit
  15:     0x7f344b3bdec2 - g_application_register
  16:     0x7f344b3be28a - <unknown>
  17:     0x7f344b3be5e6 - g_application_run
  18:     0x555ff1ebbae5 - <unknown>
  19:     0x555ff1eb4cfe - <unknown>
  20:     0x555ff1eb2043 - <unknown>
  21:     0x555ff1eb2c28 - <unknown>
  22:     0x7f344aedd5b0 - __libc_start_call_main
  23:     0x7f344aedd679 - __libc_start_main@GLIBC_2.2.5
  24:     0x555ff1e9ddc5 - <unknown>
  25:                0x0 - <unknown>

**Comment by vars1ty** [comment]
Can you post your `style.css`? Might be an issue in there as style errors usually never occur unless it was by user error

**Comment by fearlessgeekmedia** [comment]
Well now I feel like an idiot. I assumed the build would pull a default config and it did not. LOL. But I just copied the example config into ~/.config/HybridBar and it worked. So the problem was user error. :)

**Comment by vars1ty** [comment]
Yeah thought so, gonna make so it uses the example config as a fallback 👍🏽
