### ISSUE TITLE
config on how to implement work spaces?

### ISSUE THREAD

**Issue by JaKooLit** [vars1ty/HybridBar#39]
Hi Saw there is some request regarding work space and some window

 " [Feature] Implement Hyprland Workspaces #37 "

how can I put that in config?

Thanks

**Comment by vars1ty** [comment]
Add this to the `hybrid` section in your config: `"features": ["hyprland"]`.

Then to display the current window for example, use a label with the command set to `%hl_window%` and it should work 👍🏽 
If you encounter any issues with it or have any suggestions, lmk.

**Comment by JaKooLit** [comment]
thanks alot it works... well it would be nice to have like modules like from waybar :)

**Comment by vars1ty** [comment]
What modules in particular? Most can be scripted manually

**Comment by vars1ty** [comment]
For Hyprland? Possibly, might look into it in the near future

**Comment by JaKooLit** [comment]
yup for Hyprland. Im closing this as it was already solved. Thanks for your support. Ill open another if I have more suggestions
