### ISSUE TITLE
[Packaging] new tag every AUR package update

### ISSUE THREAD

**Issue by pinkcreeper100** [vars1ty/HybridBar#8]
would help with #7

**Comment by vars1ty** [comment]
Will look into it later today or tomorrow

**Comment by vars1ty** [comment]
fuck forgot ab this mb, pinning it so i don't forget for later today.

**Comment by vars1ty** [comment]
Tag 0.2.0 is now available, will make new ones for each new release. If I forget about it, feel free to create a new issue regarding it.
